### ISSUE TITLE
Interacting throws hundreds of console errors

### ISSUE THREAD

**Issue by derekperkins** [cmudig/mosaic-profiler#33]
Interacting with this parquet file, https://dig.cmu.edu/mosaic-profiler/#url=https://idl.uw.edu/mosaic/data/athletes.parquet, cross-filtering by interacting with any draggable crosshairs throws an error on almost every pixel during the drag.

<img width="727" alt="image" src="https://github.com/user-attachments/assets/786bf737-cfaa-40ca-8042-9803a6a14628">

```js
TypeError: Cannot read properties of undefined (reading 'source')
    at v (2.CYdY-Tyc.js:84:621)
    at MutationObserver.O (2.CYdY-Tyc.js:84:2097)
```

**Comment by JessamineQ** [comment]
Thanks for pointing this out! I believe these errors are now resolved in #34

**Comment by domoritz** [comment]
Can we close this issue then?

**Comment by derekperkins** [comment]
Looks great, I confirmed that there are no more errors emitted to the console.
